name: check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: install rust
        run: |
          rustup toolchain install 1.94.1 --profile minimal --component rustfmt,clippy
          rustup default 1.94.1
      - name: check
        run: make check
